package com.patrickma.magiccircles.worldgen;

import com.patrickma.magiccircles.MagicCircles;
import com.patrickma.magiccircles.block.MagicCircleBlock;
import com.patrickma.magiccircles.block.RuneColor;
import com.patrickma.magiccircles.registry.ModBlocks;
import com.patrickma.magiccircles.ritual.MagicCircleRitual;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.Half;
import net.minecraft.world.level.block.state.properties.Property;
import net.minecraft.world.level.saveddata.SavedData;
import net.minecraftforge.event.server.ServerStartedEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ForgeRegistries;
import org.slf4j.Logger;
import com.mojang.logging.LogUtils;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Random;
import java.util.zip.GZIPInputStream;

/**
 * The World Tree - a single, massive, permanent "God Tree" house standing at the exact center
 * of the Fairy Realm island (world X/Z 0,0). Unlike the mod's other worldgen (the flat island
 * disc, procedural), this one is a real player-built structure: a professional builder's tree
 * house, captured block-for-block from their own world save and baked into this mod as a
 * compact resource (see {@code data/magiccircles/structures/god_tree.bin.gz} -
 * {@value #STRUCTURE_RESOURCE}) rather than generated by any algorithm here. An earlier version
 * of this was a hand-written procedural tree (a cylinder trunk, sphere leaf clusters, straight
 * diagonal branches); it worked, but looked exactly like what it was - simple geometry - next to
 * this.
 *
 * <p><b>Placement is a one-time world edit, not a per-chunk worldgen hook.</b> At ~487,000
 * blocks spanning roughly 10x10 chunks, this is far too large to paste from inside
 * {@code ChunkGenerator#fillFromNoise} - that's called per-chunk with only a small
 * region of nearby chunks actually accessible, nowhere near enough for a structure this wide.
 * Instead, {@link #placeIfNeeded} runs once, the first time the server ever starts with this
 * mod installed (checked via a tiny {@link GodTreeSavedData} flag persisted on the Fairy
 * Realm's own level, so it's never repeated on subsequent restarts): it force-loads every chunk
 * the structure and its well touch, then writes each block directly via
 * {@code ServerLevel#setBlock} - a plain one-time world edit on an already-existing level, with
 * none of the chunk-generation-time access restrictions.
 *
 * <p>{@link #carveWell} runs immediately after placement, replacing a 9x9 area at the trunk's
 * base with a decorated well full of Wellspring Water (see {@code ModFluids#WELLSPRING_WATER}) -
 * the actual functional Wellspring {@code HeartSpell#MANA_FONT} checks for, tagged via
 * {@code ModBlockTags#WELLSPRING}.
 */
@Mod.EventBusSubscriber(modid = MagicCircles.MOD_ID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public final class WorldTree
{
    private static final Logger LOGGER = LogUtils.getLogger();

    public static final int CENTER_X = 0;
    public static final int CENTER_Z = 0;

    private static final String STRUCTURE_RESOURCE = "/data/" + MagicCircles.MOD_ID + "/structures/god_tree.bin.gz";

    // Where the structure's own relative (0,0,0) corner lands in world space, chosen so the
    // trunk's actual center (found by scanning the source save for its wood-block bounding box)
    // ends up at CENTER_X/CENTER_Z, and the trunk's own base sits right at ground level.
    private static final int OFFSET_X = -78;
    // Was 95 - confirmed by parsing the structure resource directly (see
    // tools/diagnose scratch script referenced in the README) that the structure's own embedded
    // ground plane (its topmost block at columns away from the trunk, e.g. minecraft:grass_block)
    // sits at world Y=103 with OFFSET_Y=95, one block above the island's own topmost solid layer
    // (Y=102, from FairyRealmChunkGenerator's BASE_Y+LAYERS.length-1) - exactly the "ground below
    // the tree isn't level with the rest of the realm" seam that was reported. 94 lands that same
    // embedded ground plane at Y=102, flush with the island.
    private static final int OFFSET_Y = 94;
    private static final int OFFSET_Z = -76;

    // The well's own footprint, offset from the tree's center rather than centered on it - an
    // explicit correction after the well's first placement read as poorly positioned relative to
    // the tree's own base geometry. Unlike OFFSET_Y above, the well's vertical position
    // (see #carveWell) is anchored directly to FairyRealmChunkGenerator#groundY - the real,
    // independently-correct island surface - rather than to anything about the tree structure's
    // own coordinates, so it was never affected by the OFFSET_Y bug and doesn't need its own
    // vertical correction.
    private static final int WELL_CENTER_X = CENTER_X + 2;
    private static final int WELL_CENTER_Z = CENTER_Z + 1;
    // The well's whole assembly (rim, corners, water, floor) sits this far below the island's
    // normal walkable ground level - a deliberate sink so it reads as a proper recessed basin
    // (a small step down to reach the rim, then down again to the water) rather than a box
    // sitting flush with the surrounding grade.
    private static final int WELL_Y_OFFSET = 2;
    private static final int WELL_RADIUS = 4; // 9x9 total
    private static final int WELL_DEPTH = 8;
    // How many blocks above the well's water surface get force-cleared to air, over the interior
    // 7x7 only (not the rim/corner wall, which intentionally stays solid there) - the source
    // structure had its own floor (carpet included) passing near the well's spot at a height
    // #carveWell's own rim/corner overwrite never reached, which left that floor floating over
    // the water untouched. Bumped from 2 to 3 blocks once the well itself moved down (WELL_Y_OFFSET)
    // and so has that much further to clear before reaching open air.
    private static final int WELL_CLEARANCE_ABOVE = 6;

    private static Map<BlockPos, BlockState> cachedBlocks;
    private static int cachedMaxRadius;
    private static int cachedTopY;
    private static int cachedBottomY;
    // The structure's own full bounding box, in world coordinates - used by #clearInterior to
    // know which volume to scrub, beyond just the blocks actually captured (see that method).
    private static int cachedMinX, cachedMaxX, cachedMinZ, cachedMaxZ;

    private WorldTree()
    {
    }

    /** Runs the one-time placement (and well-carving) the first time the Fairy Realm's own level reports it hasn't happened yet. */
    @SubscribeEvent
    public static void onServerStarted(ServerStartedEvent event)
    {
        ServerLevel fairyRealm = event.getServer().getLevel(com.patrickma.magiccircles.registry.ModDimensions.FAIRY_REALM);
        if (fairyRealm != null)
        {
            // Must run before the getChunk calls below - see FairyRealmChunkGenerator#ensureTerrainReady.
            FairyRealmChunkGenerator.ensureTerrainReady(fairyRealm);
            placeIfNeeded(fairyRealm);
        }
    }

    /** How far from center any placed block reaches, at most - the client wisp system's outer orbit bound (see {@code WorldTreeWisps}). */
    public static synchronized int maxRadius()
    {
        ensureLoaded();
        return cachedMaxRadius;
    }

    /** World Y of the structure's topmost block. */
    public static synchronized int topY()
    {
        ensureLoaded();
        return cachedTopY;
    }

    /** World Y of the structure's bottommost block (below-ground roots/foundation, if any). */
    public static synchronized int bottomY()
    {
        ensureLoaded();
        return cachedBottomY;
    }

    /** Ground height (world Y) the tree is built from - see {@code FairyRealmChunkGenerator#groundY}. */
    public static int groundY()
    {
        return FairyRealmChunkGenerator.groundY();
    }

    /** World-space center of the well - offset from the tree's own center (see {@link #WELL_CENTER_X}/{@link #WELL_CENTER_Z}), {@value #WELL_Y_OFFSET} blocks below ground level (see {@link #WELL_Y_OFFSET}). */
    public static BlockPos wellCenter()
    {
        return new BlockPos(WELL_CENTER_X, groundY() - WELL_Y_OFFSET, WELL_CENTER_Z);
    }

    /**
     * Public (not just called from {@link #onServerStarted}) specifically so {@link
     * FairyPortalRuins} can call this directly before its own placement - two independent
     * {@code @SubscribeEvent} handlers have no guaranteed order relative to each other, but
     * {@code FairyPortalRuins}' own path-paving reads the *live* world surface near the tree
     * (see its own {@code pavePathToTree}), which needs the tree to have actually been placed
     * first. An explicit call here removes any dependence on Forge's own event dispatch order.
     */
    // Deliberately NOT synchronized, unlike #maxRadius/#ensureLoaded - this method's own
    // chunk-force-loading calls (getChunk) can trigger, on a *different* (worker) thread, feature
    // placement that reentrantly calls #maxRadius (see FairyLandmarkExclusionFilter). If this
    // method held WorldTree.class's own monitor for its entire body the way those two still do,
    // that worker thread would block trying to acquire the very same monitor to compute
    // #maxRadius, while this thread sits here waiting (via getChunk) for that worker to finish -
    // a real, reproducible deadlock (confirmed via a hung-server watchdog crash pointing at
    // exactly this cycle). onServerStarted only ever calls this once, synchronously, from the
    // server thread - the {@code saved.placed} flag below is the only guard this ever actually
    // needed.
    public static void placeIfNeeded(ServerLevel fairyRealm)
    {
        GodTreeSavedData saved = fairyRealm.getDataStorage().computeIfAbsent(GodTreeSavedData::load, GodTreeSavedData::new, "magiccircles_god_tree");
        if (saved.placed)
        {
            return;
        }

        ensureLoaded();
        LOGGER.info("Placing the World Tree ({} blocks) in the Fairy Realm - this happens once, ever.", cachedBlocks.size());

        int minChunkX = Integer.MAX_VALUE, maxChunkX = Integer.MIN_VALUE, minChunkZ = Integer.MAX_VALUE, maxChunkZ = Integer.MIN_VALUE;
        for (BlockPos pos : cachedBlocks.keySet())
        {
            minChunkX = Math.min(minChunkX, pos.getX() >> 4);
            maxChunkX = Math.max(maxChunkX, pos.getX() >> 4);
            minChunkZ = Math.min(minChunkZ, pos.getZ() >> 4);
            maxChunkZ = Math.max(maxChunkZ, pos.getZ() >> 4);
        }
        int wellChunkRadius = (WELL_RADIUS >> 4) + 1;
        minChunkX -= wellChunkRadius;
        maxChunkX += wellChunkRadius;
        minChunkZ -= wellChunkRadius;
        maxChunkZ += wellChunkRadius;
        for (int cx = minChunkX; cx <= maxChunkX; cx++)
        {
            for (int cz = minChunkZ; cz <= maxChunkZ; cz++)
            {
                fairyRealm.getChunk(cx, cz);
            }
        }

        for (Map.Entry<BlockPos, BlockState> entry : cachedBlocks.entrySet())
        {
            fairyRealm.setBlock(entry.getKey(), entry.getValue(), 2);
        }

        clearInterior(fairyRealm);
        carveWell(fairyRealm);
        placeAbandonedManaFontRitual(fairyRealm);
        WorldEditRelight.relight(fairyRealm, minChunkX, maxChunkX, minChunkZ, maxChunkZ);
        WellspringOcean.carveIfNeeded(fairyRealm);
        spawnAncientHeartstone(fairyRealm);
        spawnPixies(fairyRealm);
        spawnDreamElks(fairyRealm);

        saved.placed = true;
        saved.setDirty();
        LOGGER.info("World Tree placement complete.");
    }

    /**
     * Clears every position within the structure's own bounding box that ISN'T part of the
     * captured structure back to air - the compact format only ever recorded non-air blocks
     * (see the class doc comment), so anything not in {@link #cachedBlocks} was genuinely air
     * in the source build, whether that's open sky above the canopy or a hollow room inside the
     * trunk. Without this, the placement loop above is purely additive (it only ever adds
     * blocks, never removes any) - whatever the chunks already had before the tree was pasted
     * over them stays exactly where it was, including inside the tree's own hollow interior
     * spaces. That's exactly what "the interior of the tree is full of jungle leaves" turned out
     * to be: the biome's own big-jungle-tree feature had already scattered real trees through
     * that whole area (this is, after all, ordinary terrain until the tree is placed on top of
     * it) well before this one-time event ever ran, and a purely-additive placement had no way
     * to remove any of it.
     *
     * <p>This is a genuinely large volume - the bounding box is roughly
     * {@code (maxX-minX) * (maxY-minY) * (maxZ-minZ)} cells, several times the ~487k blocks
     * actually captured - but the {@code isAir()} check keeps the actual write count far lower
     * in practice, since most of that volume already is air (open sky well above the canopy)
     * even before this runs.
     *
     * <p>Restricted to a circle ({@link #cachedMaxRadius}, the same reach {@link #maxRadius()}
     * reports) around the tree's own center rather than the full rectangular bounding box: the
     * captured structure's real footprint is round-ish (a tree canopy), but its bounding box is a
     * square, so scrubbing the *whole* box left the ground at the box's own corners - genuinely
     * flat, untouched terrain nowhere near the actual tree - carved out into visibly square
     * notches. Skipping cells outside the circle just leaves whatever was already there
     * (untouched ground, most likely) rather than clearing it; it never skips an actual captured
     * block, since those are placed unconditionally above regardless of this method.
     */
    private static void clearInterior(ServerLevel level)
    {
        BlockPos.MutableBlockPos cursor = new BlockPos.MutableBlockPos();
        BlockState air = Blocks.AIR.defaultBlockState();
        int cleared = 0;
        for (int x = cachedMinX; x <= cachedMaxX; x++)
        {
            for (int z = cachedMinZ; z <= cachedMaxZ; z++)
            {
                double dist = Math.sqrt((double) (x - CENTER_X) * (x - CENTER_X) + (double) (z - CENTER_Z) * (z - CENTER_Z));
                if (dist > cachedMaxRadius)
                {
                    continue;
                }
                for (int y = cachedBottomY; y <= cachedTopY; y++)
                {
                    cursor.set(x, y, z);
                    if (cachedBlocks.containsKey(cursor))
                    {
                        continue;
                    }
                    if (!level.getBlockState(cursor).isAir())
                    {
                        level.setBlock(cursor, air, 2);
                        cleared++;
                    }
                }
            }
        }
        LOGGER.info("Cleared {} non-captured blocks inside the World Tree's own radius back to air.", cleared);
    }

    // The 5-block-wide notch (centered on the rim's own middle) where the wall becomes a
    // staircase instead - on the -X side, the side facing {@link #placeAbandonedManaFontRitual}'s
    // own ritual circle, per an explicit request for an easy way to climb in and out right there.
    private static final int WELL_STAIR_SPAN = 2;

    private static BlockState randomStoneBrickVariant(Random random)
    {
        return random.nextBoolean() ? Blocks.MOSSY_STONE_BRICKS.defaultBlockState() : Blocks.STONE_BRICKS.defaultBlockState();
    }

    private static BlockState randomStoneBrickStairs(Random random, Direction facing)
    {
        Block stairs = random.nextBoolean() ? Blocks.MOSSY_STONE_BRICK_STAIRS : Blocks.STONE_BRICK_STAIRS;
        return stairs.defaultBlockState().setValue(StairBlock.FACING, facing).setValue(StairBlock.HALF, Half.BOTTOM);
    }

    /**
     * Replaces a 9x9 area near the trunk's base (see {@link #WELL_CENTER_X}/{@link
     * #WELL_CENTER_Z}) with a decorated well: a stone-brick rim (with a Sea Lantern at each
     * corner for a bit of magical glow) around a 7x7 shaft, carved down {@value #WELL_DEPTH}
     * blocks and filled with Wellspring Water - the actual functional Wellspring, tagged via
     * {@code ModBlockTags#WELLSPRING}. The interior 7x7's own {@value #WELL_CLEARANCE_ABOVE}
     * blocks of air above the water are force-cleared too, regardless of what the source
     * structure had there - see {@link #WELL_CLEARANCE_ABOVE}'s own doc comment. The rim itself
     * is a random mix of plain and mossy stone brick, block by block, rather than uniformly one
     * or the other - matches the same randomized treatment {@link #placeAbandonedManaFontRitual}
     * gives its own stone-brick floor.
     */
    private static void carveWell(ServerLevel level)
    {
        int groundY = groundY() - WELL_Y_OFFSET;
        BlockState cornerLight = Blocks.SEA_LANTERN.defaultBlockState();
        BlockState wellspringWater = ModBlocks.WELLSPRING_WATER.get().defaultBlockState();
        BlockState floor = Blocks.CHISELED_STONE_BRICKS.defaultBlockState();
        Random random = new Random(20260907L * 7L);

        for (int dx = -WELL_RADIUS; dx <= WELL_RADIUS; dx++)
        {
            for (int dz = -WELL_RADIUS; dz <= WELL_RADIUS; dz++)
            {
                BlockPos top = new BlockPos(WELL_CENTER_X + dx, groundY, WELL_CENTER_Z + dz);
                boolean isCorner = Math.abs(dx) == WELL_RADIUS && Math.abs(dz) == WELL_RADIUS;
                boolean isRim = Math.abs(dx) == WELL_RADIUS || Math.abs(dz) == WELL_RADIUS;
                boolean isStairNotch = dx == -WELL_RADIUS && Math.abs(dz) <= WELL_STAIR_SPAN;
                if (isCorner)
                {
                    for (int dy = 0; dy < WELL_DEPTH; dy++)
                    {
                        level.setBlock(top.below(dy), randomStoneBrickVariant(random), 2);
                    }
                    level.setBlock(top, cornerLight, 2);
                    level.setBlock(top.above(), cornerLight, 2);
                    // The rim's own top surface (top.above()) sits one block below the tree's real
                    // floor (groundY()) - the source structure's own carpet/furniture, never
                    // touched by anything above, was left floating right there. Clear it.
                    level.setBlock(top.above(2), Blocks.AIR.defaultBlockState(), 2);
                }
                else if (isRim)
                {
                    for (int dy = 0; dy < WELL_DEPTH; dy++)
                    {
                        level.setBlock(top.below(dy), randomStoneBrickVariant(random), 2);
                    }
                    if (isStairNotch)
                    {
                        // A stair's FACING is the side its raised half sits on, so it's the
                        // direction you'd climb. This notch is on the well's -X edge and is meant
                        // to be walked *into* (eastward, down toward the water), so it faces WEST -
                        // low step on the inside, tall side out. Facing it EAST, as it was, put the
                        // step the wrong way round and made the rim rise as you walked in.
                        level.setBlock(top.above(), randomStoneBrickStairs(random, Direction.WEST), 2);
                    }
                    else
                    {
                        level.setBlock(top.above(), randomStoneBrickVariant(random), 2);
                    }
                    level.setBlock(top.above(2), Blocks.AIR.defaultBlockState(), 2);
                }
                else
                {
                    for (int dy = 0; dy < WELL_DEPTH; dy++)
                    {
                        level.setBlock(top.below(dy), wellspringWater, 2);
                    }
                    level.setBlock(top.below(WELL_DEPTH), floor, 2);
                    for (int dy = 1; dy <= WELL_CLEARANCE_ABOVE; dy++)
                    {
                        level.setBlock(top.above(dy), Blocks.AIR.defaultBlockState(), 2);
                    }
                }
            }
        }
    }

    /** How far above {@link #wellCenter()} the Ancient Heartstone floats - see {@code client/AncientHeartstoneWisps}, which traces its own dormant orbit at exactly this same height. */
    public static final double ANCIENT_HEARTSTONE_HEIGHT = 4.0;

    /**
     * The permanent gold heart above the well - see {@code entity/AncientHeartstoneEntity}'s own
     * doc comment. Placed {@value #ANCIENT_HEARTSTONE_HEIGHT} blocks above {@link #wellCenter()} -
     * comfortably in the middle of {@code client/WellspringWisps}' own existing ambient orbit band
     * (already 1-4.5 blocks above this same point), which is what makes those wisps read as
     * circling *this* rather than needing any change to that system at all.
     */
    private static void spawnAncientHeartstone(ServerLevel level)
    {
        BlockPos wellCenter = wellCenter();
        com.patrickma.magiccircles.entity.AncientHeartstoneEntity heart =
                new com.patrickma.magiccircles.entity.AncientHeartstoneEntity(
                        com.patrickma.magiccircles.registry.ModEntities.ANCIENT_HEARTSTONE.get(), level);
        heart.setPos(wellCenter.getX() + 0.5, wellCenter.getY() + ANCIENT_HEARTSTONE_HEIGHT, wellCenter.getZ() + 0.5);
        level.addFreshEntity(heart);
    }

    // A guaranteed population at world-init, rather than relying solely on NaturalSpawner's own
    // ongoing biome spawn cycle (see SpawnPlacements.register in MagicCircles#commonSetup, and
    // PixiePopulationMaintainer for the *ongoing* guarantee - natural spawning alone was
    // confirmed, by the person actually playing this, to never produce a single pixie in
    // practice). A real, direct placement is the only way to be *certain* the realm never starts
    // pixie-less, regardless of whatever spawn-cap/density/heightmap factors might otherwise
    // suppress natural spawns entirely.
    private static final int PIXIE_POPULATION = 60;

    private static void spawnPixies(ServerLevel level)
    {
        Random random = new Random(20260907L * 5L);
        for (int i = 0; i < PIXIE_POPULATION; i++)
        {
            spawnOnePixie(level, random);
        }
    }

    /**
     * Picks a genuinely open spot (a real 1x2 air pocket, not just "within some radius of the
     * tree") and spawns one pixie there - shared by the world-init population above and {@code
     * PixiePopulationMaintainer}'s own ongoing top-ups. An earlier version picked X/Z within
     * {@code PIXIE_SPAWN_RADIUS} of the tree and a Y just a few blocks above ground with no
     * placement check at all - since the World Tree's own trunk/canopy fills most of that same
     * volume near its center, the large majority of "spawned" pixies actually landed embedded
     * *inside* solid wood/leaves, taking constant suffocation damage (read as "constantly making
     * the dying sound," which is really the hurt sound firing every tick it stayed stuck).
     *
     * <p>Sampling height across the tree's own real vertical span ({@link #groundY()} up past
     * {@link #topY()}) rather than a fixed low band is what actually gives {@link
     * #isOpenAirPocket} a real chance of finding open space near a structure this tall - most
     * genuinely open air near the tree is up among/above the canopy, not in the first few blocks
     * above the ground where the trunk and low branches actually are.
     */
    public static boolean spawnOnePixie(ServerLevel level, Random random)
    {
        int radius = maxRadius() + 20;
        int minY = groundY() + 1;
        int maxY = topY() + 25;
        for (int attempt = 0; attempt < 40; attempt++)
        {
            double angle = random.nextDouble() * 2.0 * Math.PI;
            double dist = random.nextDouble() * radius;
            int x = CENTER_X + (int) Math.round(Math.cos(angle) * dist);
            int z = CENTER_Z + (int) Math.round(Math.sin(angle) * dist);
            int y = minY + random.nextInt(Math.max(1, maxY - minY));

            if (!isOpenAirPocket(level, x, y, z))
            {
                continue;
            }

            com.patrickma.magiccircles.entity.PixieEntity pixie =
                    new com.patrickma.magiccircles.entity.PixieEntity(com.patrickma.magiccircles.registry.ModEntities.PIXIE.get(), level);
            pixie.moveTo(x + 0.5, y, z + 0.5, random.nextFloat() * 360.0f, 0.0f);
            pixie.finalizeSpawn(level, level.getCurrentDifficultyAt(pixie.blockPosition()), net.minecraft.world.entity.MobSpawnType.COMMAND, null, null);
            level.addFreshEntity(pixie);
            return true;
        }
        return false;
    }

    /** The area {@code PixiePopulationMaintainer} counts existing pixies within, to decide how many (if any) more to top up - generously wider/taller than the tree's own real footprint so pixies that have wandered off (per their own {@code PixieFlyNearTreeGoal}) still count toward the target instead of being spawned on top of. */
    public static net.minecraft.world.phys.AABB populationCheckArea()
    {
        int radius = maxRadius() + 60;
        return new net.minecraft.world.phys.AABB(CENTER_X - radius, bottomY() - 20, CENTER_Z - radius,
                CENTER_X + radius, topY() + 60, CENTER_Z + radius);
    }

    /**
     * A real 1x2 (feet + head) air pocket - not embedded in a tree trunk/canopy/leaves. Doesn't
     * require solid ground underfoot: a pixie flies (the same way an Allay does), so open sky well
     * above the actual terrain is a perfectly valid spot, not just a surface to stand on - an
     * earlier version of this check required solid ground directly below too, which rejected most
     * of the genuinely open air high up near/above the canopy (exactly where pixies are meant to
     * fly per {@link PixieEntity.PixieFlyNearTreeGoal}) and left over a third of the world-init
     * population unable to find anywhere to spawn at all within a reasonable number of attempts.
     */
    private static boolean isOpenAirPocket(ServerLevel level, int x, int y, int z)
    {
        BlockPos feet = new BlockPos(x, y, z);
        return level.getBlockState(feet).isAir() && level.getBlockState(feet.above()).isAir();
    }

    // A guaranteed land population, the same reasoning as PIXIE_POPULATION above - the only
    // Dream Elk placed so far were the handful WellspringOcean drops deep in the underground
    // ocean (see that class's own doc comment on why *those* specifically can't come from
    // natural spawning at all), which is a real but easy-to-never-actually-find population on
    // its own. This is the "you can actually just walk up and see one" guarantee, on the open
    // grass around the tree - same helping hand as the pixies got.
    private static final int DREAM_ELK_LAND_POPULATION = 12;

    private static void spawnDreamElks(ServerLevel level)
    {
        Random random = new Random(20260907L * 11L);
        int placed = 0;
        for (int attempt = 0; attempt < DREAM_ELK_LAND_POPULATION * 25 && placed < DREAM_ELK_LAND_POPULATION; attempt++)
        {
            double angle = random.nextDouble() * 2.0 * Math.PI;
            // Just past the tree's own real footprint, out on the surrounding flat grass -
            // never inside the tree's own trunk/canopy area at all.
            double dist = maxRadius() + 10 + random.nextDouble() * 40;
            int x = CENTER_X + (int) Math.round(Math.cos(angle) * dist);
            int z = CENTER_Z + (int) Math.round(Math.sin(angle) * dist);
            int y = groundY();

            if (!isSolidGroundPocket(level, x, y, z))
            {
                continue;
            }

            com.patrickma.magiccircles.entity.DreamElkEntity elk =
                    new com.patrickma.magiccircles.entity.DreamElkEntity(com.patrickma.magiccircles.registry.ModEntities.DREAM_ELK.get(), level);
            elk.moveTo(x + 0.5, y, z + 0.5, random.nextFloat() * 360.0f, 0.0f);
            elk.finalizeSpawn(level, level.getCurrentDifficultyAt(elk.blockPosition()), net.minecraft.world.entity.MobSpawnType.COMMAND, null, null);
            level.addFreshEntity(elk);
            placed++;
        }
    }

    /** A real 2-tall air pocket over solid ground - unlike {@link #isOpenAirPocket}, Dream Elk walk rather than fly, so they actually need footing, not just open sky. */
    private static boolean isSolidGroundPocket(ServerLevel level, int x, int y, int z)
    {
        BlockPos feet = new BlockPos(x, y, z);
        return level.getBlockState(feet).isAir()
                && level.getBlockState(feet.above()).isAir()
                && !level.getBlockState(feet.below()).isAir();
    }

    /**
     * A second magic circle inside the tree's own interior, away from the well - drawn as though
     * someone had set up to charge a Heartstone (a Purple+Green ring, the exact combo {@code
     * HeartSpell#comboFor} resolves to Mana Font) and simply never placed the stone: a complete,
     * valid ring with nothing but a plain rune at its own center, no Heart Core here at all.
     * Positioned by counting outward from the well itself - {@value #WELL_RADIUS} blocks to clear
     * the well's own rim, then 3 more past it, straight out along -X - and one block above the
     * tree's own interior floor ({@link #groundY()}), clearing whatever carpet/furniture the
     * captured structure happened to leave in that 5x5 patch first. The floor underneath is a
     * random mix of plain and mossy stone brick, matching the well's own rim treatment.
     */
    private static void placeAbandonedManaFontRitual(ServerLevel level)
    {
        int centerX = WELL_CENTER_X - WELL_RADIUS - 3;
        int centerZ = WELL_CENTER_Z;
        int floorY = groundY();

        Random random = new Random(20260908L);
        for (int dx = -2; dx <= 2; dx++)
        {
            for (int dz = -2; dz <= 2; dz++)
            {
                level.setBlock(new BlockPos(centerX + dx, floorY, centerZ + dz), Blocks.AIR.defaultBlockState(), 2);
                level.setBlock(new BlockPos(centerX + dx, floorY - 1, centerZ + dz), randomStoneBrickVariant(random), 2);
            }
        }

        for (int i = 0; i < MagicCircleRitual.RING_OFFSETS.length; i++)
        {
            int[] offset = MagicCircleRitual.RING_OFFSETS[i];
            // Even/odd alternation over 12 positions is exactly a 6-6 split, per HeartSpell#comboFor.
            RuneColor color = i % 2 == 0 ? RuneColor.PURPLE : RuneColor.GREEN;
            BlockPos pos = new BlockPos(centerX + offset[0], floorY, centerZ + offset[1]);
            level.setBlock(pos, ModBlocks.MAGIC_CIRCLE.get().defaultBlockState()
                    .setValue(MagicCircleBlock.VARIANT, random.nextInt(MagicCircleBlock.VARIANT_COUNT))
                    .setValue(MagicCircleBlock.COLOR, color), 2);
        }
        // The center - a plain rune, not a Heart Core: the ring is complete and castable, but
        // nobody ever placed a Heartstone on it.
        level.setBlock(new BlockPos(centerX, floorY, centerZ), ModBlocks.MAGIC_CIRCLE.get().defaultBlockState()
                .setValue(MagicCircleBlock.VARIANT, random.nextInt(MagicCircleBlock.VARIANT_COUNT))
                .setValue(MagicCircleBlock.COLOR, RuneColor.PURPLE), 2);
    }

    private static synchronized void ensureLoaded()
    {
        if (cachedBlocks != null)
        {
            return;
        }
        Map<BlockPos, BlockState> blocks = new HashMap<>();
        int minX = Integer.MAX_VALUE, maxX = Integer.MIN_VALUE;
        int minY = Integer.MAX_VALUE, maxY = Integer.MIN_VALUE;
        int minZ = Integer.MAX_VALUE, maxZ = Integer.MIN_VALUE;

        try (InputStream raw = WorldTree.class.getResourceAsStream(STRUCTURE_RESOURCE))
        {
            if (raw == null)
            {
                throw new IOException("Resource not found: " + STRUCTURE_RESOURCE);
            }
            try (DataInputStream in = new DataInputStream(new BufferedInputStream(new GZIPInputStream(raw))))
            {
                String magic = in.readUTF();
                if (!"MCGT1".equals(magic))
                {
                    throw new IOException("Unexpected structure file header: " + magic);
                }
                in.readUnsignedByte(); // sizeX - not needed, kept for the file format's own bookkeeping
                in.readUnsignedByte(); // sizeY
                in.readUnsignedByte(); // sizeZ

                int paletteCount = in.readUnsignedShort();
                BlockState[] palette = new BlockState[paletteCount];
                for (int i = 0; i < paletteCount; i++)
                {
                    String name = in.readUTF();
                    int propertyCount = in.readUnsignedByte();
                    Map<String, String> properties = new HashMap<>();
                    for (int p = 0; p < propertyCount; p++)
                    {
                        String key = in.readUTF();
                        String value = in.readUTF();
                        properties.put(key, value);
                    }
                    palette[i] = resolveBlockState(name, properties);
                }

                int recordCount = in.readInt();
                for (int i = 0; i < recordCount; i++)
                {
                    int rx = in.readUnsignedByte();
                    int ry = in.readUnsignedByte();
                    int rz = in.readUnsignedByte();
                    int paletteIndex = in.readUnsignedShort();

                    int wx = rx + OFFSET_X;
                    int wy = ry + OFFSET_Y;
                    int wz = rz + OFFSET_Z;
                    blocks.put(new BlockPos(wx, wy, wz), palette[paletteIndex]);

                    minX = Math.min(minX, wx);
                    maxX = Math.max(maxX, wx);
                    minY = Math.min(minY, wy);
                    maxY = Math.max(maxY, wy);
                    minZ = Math.min(minZ, wz);
                    maxZ = Math.max(maxZ, wz);
                }
            }
        }
        catch (IOException e)
        {
            throw new IllegalStateException("Failed to load the World Tree structure from " + STRUCTURE_RESOURCE, e);
        }

        cachedBlocks = blocks;
        cachedTopY = maxY;
        cachedBottomY = minY;
        cachedMinX = minX;
        cachedMaxX = maxX;
        cachedMinZ = minZ;
        cachedMaxZ = maxZ;
        int reachX = Math.max(Math.abs(minX - CENTER_X), Math.abs(maxX - CENTER_X));
        int reachZ = Math.max(Math.abs(minZ - CENTER_Z), Math.abs(maxZ - CENTER_Z));
        cachedMaxRadius = Math.max(reachX, reachZ);
    }

    // Every storage container the source structure had (see the extraction scratch tooling's
    // own palette dump) - replaced with air rather than placed, so nobody has to stock a treasure
    // hoard's worth of chests/barrels/shulker boxes across a house this size just to avoid it
    // looking unfinished. The structure's own NBT inventory data was never captured in the first
    // place (see the class doc comment on the compact binary format - block-state only, no block
    // entity contents), so every one of these would already have placed empty regardless.
    private static final java.util.Set<Block> REMOVED_CONTAINERS = java.util.Set.of(
            Blocks.CHEST, Blocks.ENDER_CHEST, Blocks.BARREL, Blocks.SHULKER_BOX);

    private static BlockState resolveBlockState(String name, Map<String, String> properties)
    {
        Block block = ForgeRegistries.BLOCKS.getValue(new ResourceLocation(name));
        if (block == null)
        {
            LOGGER.warn("World Tree structure references unknown block {} - using air instead", name);
            return Blocks.AIR.defaultBlockState();
        }
        if (REMOVED_CONTAINERS.contains(block))
        {
            return Blocks.AIR.defaultBlockState();
        }
        BlockState state = block.defaultBlockState();
        StateDefinition<Block, BlockState> stateDefinition = block.getStateDefinition();
        for (Map.Entry<String, String> entry : properties.entrySet())
        {
            Property<?> property = stateDefinition.getProperty(entry.getKey());
            if (property != null)
            {
                state = applyProperty(state, property, entry.getValue());
            }
        }
        return state;
    }

    private static <T extends Comparable<T>> BlockState applyProperty(BlockState state, Property<T> property, String valueString)
    {
        Optional<T> value = property.getValue(valueString);
        return value.map(v -> state.setValue(property, v)).orElse(state);
    }

    /** Just the one boolean this needs to persist: has the World Tree already been placed on this Fairy Realm level. */
    public static final class GodTreeSavedData extends SavedData
    {
        private boolean placed;

        public GodTreeSavedData()
        {
        }

        public static GodTreeSavedData load(CompoundTag tag)
        {
            GodTreeSavedData data = new GodTreeSavedData();
            data.placed = tag.getBoolean("Placed");
            return data;
        }

        @Override
        public CompoundTag save(CompoundTag tag)
        {
            tag.putBoolean("Placed", placed);
            return tag;
        }
    }
}
