"""Generates the full-screen underwater overlay for the Wellspring's own water
(ModFluidTypes.WELLSPRING_WATER#getRenderOverlayTexture) - replaces an earlier "rainbow band per
column" version (kept the ring-color-cycling idea from the Wellspring's own block texture, but
read as visually chaotic and was never actually asked for as "rainbow" - the user wants a light
blue tint here instead, similar to how real ocean water tints the screen, distinct from the
portal fluid's own pale near-white filter (ModFluidTypes.PORTAL_WATER, generated by
gen_portal_underwater_overlay.py) which stays completely unchanged.

Run from anywhere with `python tools/gen_wellspring_underwater_overlay.py` (requires Pillow).
Same 16x16 tile size and rendering path as the portal overlay (see
client/ModFluidOverlayRenderer.java - alpha here is the real, only multiplier, not the capped 10%
vanilla's own default renderOverlay would apply) - a light, moderately saturated blue rather than
vanilla's own quite-saturated (31-61, 85-109, 255) underwater.png, since without that hidden 10%
cap a color that saturated would read as overwhelming at any alpha strong enough to be visible at
all.
"""
import os
import random

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEX_DIR = os.path.join(ROOT, "src", "main", "resources", "assets", "magiccircles", "textures", "misc")
os.makedirs(TEX_DIR, exist_ok=True)

SIZE = 16
DARK = (60, 130, 200)
LIGHT = (100, 170, 230)
ALPHA_LOW = 90
ALPHA_HIGH = 115


def main():
    random.seed(20260908)
    img = Image.new("RGBA", (SIZE, SIZE))
    for y in range(SIZE):
        for x in range(SIZE):
            color = DARK if random.random() < 0.5 else LIGHT
            alpha = random.randint(ALPHA_LOW, ALPHA_HIGH)
            img.putpixel((x, y), color + (alpha,))

    tex_path = os.path.join(TEX_DIR, "wellspring_underwater.png")
    img.save(tex_path)
    print(f"Wrote {tex_path}")


if __name__ == "__main__":
    main()
