"""Generates the six chalk items as 3D sticks - a 16x16 texture and an element model for each:

  textures/item/<name>.png   - the chalk's surface, laid out in regions the model's faces sample
  models/item/<name>.json    - a 4x4 stick ten pixels long with a narrower, worn tip

Each chalk is coloured through and through in its own rune colour, not a white stick with a band.

Texture layout (pixels), matching the UVs in MODEL below:
  x 0-3,  y 0-9   the stick's four sides: the colour, faint lengthwise streaks and specks
  x 4-7,  y 0-3   the broken bottom end: a shade darker, rougher
  x 4-7,  y 4-7   the top shoulder around the tip: dusty, a shade lighter
  x 8-10, y 0-2   the worn tip's face: lightest - rubbed smooth from drawing
  x 8-10, y 4-5   the tip's sides: between the two
Everything else is filled with the side pattern so nothing samples a gap.
"""
import json
import random
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent / "src/main/resources/assets/magiccircles"

# Base colour of each chalk - the rune colour, as something you could draw with.
CHALKS = {
    "chalk": (74, 128, 214),          # Blue Chalk
    "gold_chalk": (226, 176, 58),
    "purple_chalk": (148, 92, 212),
    "red_chalk": (206, 70, 62),
    "green_chalk": (86, 176, 90),
    "black_chalk": (52, 44, 60),
}

MODEL = {
    "credit": "Generated by tools/gen_chalk_textures.py",
    "textures": {"chalk": None, "particle": None},
    "elements": [
        {
            "name": "body",
            "from": [6, 2, 6], "to": [10, 12, 10],
            "faces": {
                "north": {"uv": [0, 0, 4, 10], "texture": "#chalk"},
                "east": {"uv": [0, 0, 4, 10], "texture": "#chalk"},
                "south": {"uv": [0, 0, 4, 10], "texture": "#chalk"},
                "west": {"uv": [0, 0, 4, 10], "texture": "#chalk"},
                "up": {"uv": [4, 4, 8, 8], "texture": "#chalk"},
                "down": {"uv": [4, 0, 8, 4], "texture": "#chalk"},
            },
        },
        {
            "name": "worn tip",
            "from": [6.5, 12, 6.5], "to": [9.5, 14, 9.5],
            "faces": {
                "north": {"uv": [8, 4, 11, 6], "texture": "#chalk"},
                "east": {"uv": [8, 4, 11, 6], "texture": "#chalk"},
                "south": {"uv": [8, 4, 11, 6], "texture": "#chalk"},
                "west": {"uv": [8, 4, 11, 6], "texture": "#chalk"},
                "up": {"uv": [8, 0, 11, 3], "texture": "#chalk"},
                "down": {"uv": [8, 0, 11, 3], "texture": "#chalk"},
            },
        },
    ],
    # The stick stands along Y. In the inventory it leans up and to the right like any tool, tipped
    # toward you a little so its end shows; in the hand the angles are vanilla's handheld ones,
    # corrected for the stick running straight up rather than along the sprite's diagonal.
    "display": {
        "gui": {"rotation": [20, 20, -45], "translation": [0, 0, 0], "scale": [1.05, 1.05, 1.05]},
        "ground": {"rotation": [0, 0, 0], "translation": [0, 2, 0], "scale": [0.5, 0.5, 0.5]},
        "fixed": {"rotation": [0, 0, -45], "translation": [0, 0, 0], "scale": [1, 1, 1]},
        "thirdperson_righthand": {"rotation": [0, -90, 10], "translation": [0, 3, 0.5], "scale": [0.6, 0.6, 0.6]},
        "thirdperson_lefthand": {"rotation": [0, 90, -10], "translation": [0, 3, 0.5], "scale": [0.6, 0.6, 0.6]},
        "firstperson_righthand": {"rotation": [0, -90, -20], "translation": [1.13, 3.2, 1.13], "scale": [0.5, 0.5, 0.5]},
        "firstperson_lefthand": {"rotation": [0, 90, 20], "translation": [1.13, 3.2, 1.13], "scale": [0.5, 0.5, 0.5]},
        "head": {"rotation": [0, 0, 0], "translation": [0, 13, 7], "scale": [1, 1, 1]},
    },
}


def shade(colour, factor):
    return tuple(max(0, min(255, round(c * factor))) for c in colour)


def lift(colour, amount):
    """Mixes toward white - chalk dust, not just a brighter colour."""
    return tuple(round(c + (255 - c) * amount) for c in colour)


def texture(base, seed):
    rng = random.Random(seed)
    image = Image.new("RGBA", (16, 16))
    px = image.load()

    # Faint lengthwise streaks, one value per column, so the sides read as a pressed stick.
    column_tone = [rng.uniform(0.93, 1.05) for _ in range(16)]

    def side_pixel(x):
        tone = column_tone[x] * rng.uniform(0.96, 1.04)
        colour = shade(base, tone)
        roll = rng.random()
        if roll < 0.07:
            colour = lift(colour, 0.25)       # a fleck of loose dust
        elif roll < 0.12:
            colour = shade(colour, 0.85)      # a pit in the surface
        return colour

    for y in range(16):
        for x in range(16):
            px[x, y] = (*side_pixel(x), 255)

    # Darker toward the bottom of the sides - where fingers hold it.
    for y in range(7, 10):
        for x in range(0, 4):
            r, g, b, _ = px[x, y]
            px[x, y] = (*shade((r, g, b), 0.94 - (y - 7) * 0.02), 255)

    # Broken bottom end: darker and rough.
    for y in range(0, 4):
        for x in range(4, 8):
            px[x, y] = (*shade(base, rng.uniform(0.78, 0.9)), 255)

    # Shoulder around the tip: dusty.
    for y in range(4, 8):
        for x in range(4, 8):
            px[x, y] = (*lift(shade(base, rng.uniform(0.98, 1.04)), 0.18), 255)

    # Worn tip face: rubbed smooth and pale from drawing.
    for y in range(0, 3):
        for x in range(8, 11):
            px[x, y] = (*lift(base, rng.uniform(0.32, 0.4)), 255)

    # Tip sides.
    for y in range(4, 6):
        for x in range(8, 11):
            px[x, y] = (*lift(shade(base, rng.uniform(0.97, 1.03)), 0.2), 255)

    return image


def main():
    for index, (name, base) in enumerate(CHALKS.items()):
        tex_path = ROOT / "textures/item" / f"{name}.png"
        texture(base, seed=9000 + index).save(tex_path)

        model = json.loads(json.dumps(MODEL))
        model["textures"]["chalk"] = f"magiccircles:item/{name}"
        model["textures"]["particle"] = f"magiccircles:item/{name}"
        model_path = ROOT / "models/item" / f"{name}.json"
        model_path.write_text(json.dumps(model, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {tex_path.name} and {model_path.name}")


if __name__ == "__main__":
    main()
